name: Support Ticket
description: Use this form to submit a support ticket to UCTS
labels: support

fields:
  - type: input
    attributes:
      label: "Issue Summary"
      description: "Please describe the issue in a few sentences."
      placeholder: "Describe the issue here"
      required: true

  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: "Please outline the steps to reproduce the issue."
      required: true

  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen."
      required: true

  - type: textarea
    attributes:
      label: "Actual Behavior"
      description: "Describe what happened instead."
      required: true

  - type: textarea
    attributes:
      label: "Additional Information"
      description: "Any extra context that could help us solve the issue."
